import sys
from fpdf import FPDF

name = sys.argv[1] if len(sys.argv) > 1 else "Anonymous"

class CertificatePDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 24)
        self.cell(0, 20, "Certificate of Nothingness", ln=True, align="C")

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 10)
        self.cell(0, 10, "Generated by NothingCourse.com", 0, 0, "C")

    def add_body(self, name):
        self.ln(20)
        self.set_font("Helvetica", "", 16)
        self.cell(0, 10, "This certifies that", ln=True, align="C")
        self.ln(10)
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(34, 34, 170)
        self.cell(0, 12, name, ln=True, align="C")
        self.ln(10)
        self.set_font("Helvetica", "", 14)
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 10, "has bravely chosen to buy\n\nBuy Nothing. Learn Nothing. But feel something.", align="C")

pdf = CertificatePDF()
pdf.add_page()
pdf.add_body(name)
pdf.output("server/Certificate_of_Nothingness.pdf")
